name: calval_CSLC_ALE
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - python>=3.9
 - pip
 - boto3=1.26.54
 - dateparser
 - dask>=1.0
 - dask-jobqueue>=0.3
 - folium
 - fsspec=2023.5.0
 - geopandas
# - gdal>=3
 - h5py
 - ipympl
 - isce3
 - lxml
 - matplotlib
 - mintpy
 - netcdf4
 - numpy
 - pandas
 - pymap3d
 - pysolid
 - pyproj
 - rasterio
 - requests
 - ruamel.yaml
 - scipy
 - s3fs=2023.5.0
 - yamale
 # for testing and distribution
 - flake8
 - flake8-import-order
 - flake8-blind-except
 - flake8-builtins
 - ipykernel
 - jsonschema==3.2.0
 - jupyter
 - packaging
 - papermill
 - pytest
 - pytest-cov
 - setuptools
 - setuptools_scm
